version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      tuf-on-ci:
        patterns:
          - "theupdateframework/tuf-on-ci/actions/*"
