name: TUF-on-CI online signing

permissions: {}

on:
  schedule:
    - cron: '17 1,7,13,19 * * *'
  push:
    branches: [main]
    paths: ['metadata/**', '!metadata/timestamp.json', '!metadata/snapshot.json']
  workflow_dispatch:

jobs:
  online-sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for OIDC identity access
      contents: write # for committing snapshot/timestamp changes
      actions: write # for dispatching publish workflow
    steps:
      - id: online-sign
        uses: theupdateframework/tuf-on-ci/actions/online-sign@5105c4bd73fae36f089dd4848fd1fd81a20a3df8 # v0.16.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

  update-issue:
    runs-on: ubuntu-latest
    needs: [online-sign]
    if: always() && !cancelled()
    permissions:
      issues: write # for modifying Issues
      contents: read # for checking out the repository
    steps:
      - name: Update the issue for the workflow
        uses: theupdateframework/tuf-on-ci/actions/update-issue@5105c4bd73fae36f089dd4848fd1fd81a20a3df8 # v0.16.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
