name: TUF-on-CI signing event

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ['sign/**']
    paths: ['metadata/**', 'targets/**']

jobs:
  handle-signing-event:
    name: TUF-on-CI signing event
    runs-on: ubuntu-latest
    permissions:
      contents: write # for making commits in signing event and for modifying draft state
      pull-requests: write # for modifying signing event pull requests
      actions: write # for dispatching another signing-event workflow

    steps:
      - name: Signing event
        # if: github.repository_owner == 'insert-owner-name-here' # avoid running in forks
        uses: theupdateframework/tuf-on-ci/actions/signing-event@5105c4bd73fae36f089dd4848fd1fd81a20a3df8 # v0.16.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
